category: DevTools
compatibility:
  adonis:
    "6": 6.x
    "7": 7.x
description: Generate OpenAPI V3 compliant specifications using decorators
icon: foadonis.png
lastCommitAt: 2026-07-06T10:26:23Z
lastReleaseAt: 2026-07-06T10:27:24.652Z
latestNpmVersion: 1.1.0
name: foadonis-openapi
npm: "@foadonis/openapi"
repo: FriendsOfAdonis/FriendsOfAdonis
status: healthy
type: 3rd-party
website: https://friendsofadonis.com/docs/openapi
